version: '3.9'
services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=aslkdjl923jk2

